In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.arange(10, 101, 10)

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [3]:
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

ndim: 2
shape: (2, 3)
size: 6
dtype: int64


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])

50


In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [7]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
arr = np.array([1, 2, 3, 4, 5])

result = arr * 5

print(result)

[ 5 10 15 20 25]


In [10]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [20, 30, 40],
    [60, 70, 80]
])

print(X)
print("Shape:", X.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [20 30 40]
 [60 70 80]]
Shape: (5, 3)


In [11]:
mean = np.mean(X, axis=0)

print(mean)

[40. 50. 60.]


In [12]:
result = X[X[:, 0] > 50]

print(result)

[[70 80 90]
 [60 70 80]]


In [13]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print(X_standardized)

[[-1.31558703 -1.31558703 -1.31558703]
 [ 0.          0.          0.        ]
 [ 1.31558703  1.31558703  1.31558703]
 [-0.87705802 -0.87705802 -0.87705802]
 [ 0.87705802  0.87705802  0.87705802]]


In [14]:
np.random.seed(42)

X = np.random.rand(10, 4)

print(X)
print("Shape:", X.shape)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]
Shape: (10, 4)


In [15]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

weights = np.array([10, 20, 30])

result = X @ weights

print(result)

[140 320]


In [16]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

bias = np.array([1, 2, 3])

result = X + bias

print(result)

[[11 22 33]
 [41 52 63]]


In [17]:
y_true = np.array([10, 20, 30])

y_pred = np.array([12, 18, 29])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE:", mse)

MSE: 3.0


In [18]:
image = np.zeros((28, 28))

print("Shape:", image.shape)

Shape: (28, 28)


In [19]:
images = np.zeros((64, 224, 224, 3))

print("Shape:", images.shape)

Shape: (64, 224, 224, 3)


In [20]:
arr = np.array([10, 20, np.nan, 30, 40])

mean = np.nanmean(arr)

print("Mean:", mean)

Mean: 25.0


In [21]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A * B)

[[ 5 12]
 [21 32]]
